### ISSUE TITLE
npm install @coinbase/wallet-sdk# Want to try out the new smart wallet on testnet? make sure you’re using ^4.0.0# npm install @coinbase/wallet-sdk@4.0.0-beta.0

### ISSUE THREAD

**Issue by jebuto** [coinbase/cdpcurl#22]

**Comment by ALANthemoor** [comment]
https://api.developer.coinbase.com/platform/v1/wallets

**Comment by ALANthemoor** [comment]
Transfer form block chain account 
[0418dcc7-6734-4356-85ad-fd7d7c2d1783.csv](https://github.com/user-attachments/files/17973933/0418dcc7-6734-4356-85ad-fd7d7c2d1783.csv)

**Comment by ALANthemoor** [comment]
0xcebfcf91ceff932b6cb7d08aca419179c28c182f8254bf60ba6b3683caa0ebd6

**Comment by ALANthemoor** [comment]
0.009707788264 ETH
